### PR TITLE
Speedup rebased on top of merge upstream changes to main branch

### PR DESCRIPTION
**Pull request by pstibrany**
This is a rebase of `speedup` branch on top of `merge-upstream-changes-to-main` branch from PR https://github.com/grafana/regexp/pull/1

### CODE REVIEW

**Review by pracucci — COMMENTED** [review]
Can we see a diff between this PR and the upstream `main`?

**Comment by pstibrany** [comment]
> Can we see a diff between this PR and the upstream `main`?

That would be this compare (last commit on this branch compared to "[Copy files from Go 1.19.2](https://github.com/grafana/regexp/pull/2/commits/c5045a9c3695e28605a15d4c89567f2dc58a6533)":

https://github.com/grafana/regexp/compare/c5045a9..f572b3a

**Comment by pstibrany** [comment]
I converted this to a draft, as we should not merge it to `main`. We can call it `speedup2` instead.

**Comment by pstibrany** [comment]
After merging #1 I've rebased this branch on `main` and renamed it to `speedup-golang-1.19.2`. I will close this PR.

**Pull request closed without merging**
